# codecov.yml

codecov:
  ignore:
    - "/home/runner/work/edufinder/edufinder/edufinder/tests/*"
    - "edufinder/tests"
    - "edufinder/tests/test_api"

fixes:
  - "/home/runner/work/edufinder/edufinder/::" # Correct paths