# Generated by Django 3.1.2 on 2020-10-19 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationtype',
            name='name',
            field=models.CharField(max_length=120),
        ),
    ]
