# Generated by Django 3.1.2 on 2020-10-22 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_auto_20201019_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Probably', 'Probably'), ('Probably not', 'Probably Not'), ("Don't know", 'Dont Know')], max_length=20)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.question')),
                ('userAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.useranswer')),
            ],
        ),
    ]
