# Generated by Django 3.1.2 on 2020-10-26 12:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_answer_useranswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useranswer',
            name='ip_addr',
            field=models.GenericIPAddressField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='educationtype',
            name='education',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_types', to='rest_api.education'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'userAnswer')},
        ),
    ]
