# Generated by Django 3.1.2 on 2020-10-29 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_useranswer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='education',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rest_api.education'),
            preserve_default=False,
        ),
    ]
