# Generated by Django 3.1.2 on 2020-11-04 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_useranswer_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='da',
        ),
        migrations.AddField(
            model_name='question',
            name='en',
            field=models.CharField(default='asd', max_length=200),
            preserve_default=False,
        ),
    ]
