# Generated by Django 3.1.2 on 2020-11-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0008_answerconsensus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.IntegerField(choices=[(2, 'Yes'), (-2, 'No'), (1, 'Probably'), (-1, 'Probably Not'), (0, 'Dont Know')]),
        ),
        migrations.AlterField(
            model_name='answerconsensus',
            name='answer',
            field=models.IntegerField(choices=[(2, 'Yes'), (-2, 'No'), (1, 'Probably'), (-1, 'Probably Not'), (0, 'Dont Know')]),
        ),
    ]
