# Generated by Django 3.1.2 on 2020-11-11 12:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_answer_integer_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='weight',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
