name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd edufinder
          coverage run manage.py test tests
      - name: Coverage report
        run: |
          cd edufinder
          coverage report
                  make test
      - name: Upload coverage reports to Codecov
        run: |
          codecov
